#!/bin/sh

storage_dir=/home/nemo/.qmf
if [ ! -d $storage_dir ]; then
    mkdir -p $storage_dir
    if [ $? -gt 0 ]; then
        echo "could not mkdir qmf storage directory"
        exit 1
    fi
fi

chown -v privileged.privileged $storage_dir
if [ $? -gt 0 ]; then
    echo "could not chown qmf storage directory"
    exit 1
fi

chmod -v 070 $storage_dir
if [ $? -gt 0 ]; then
    echo "could not chmod qmf storage directory"
    exit 1
fi

chown -v -R nemo.privileged "$storage_dir/*"
if [ $? -gt 0 ]; then
    echo "could not chown content of qmf storage directory"
    exit 1
fi

exit 0
